const test = require('node:test')
const assert = require('node:assert/strict')
const crypto = require('node:crypto')
const fs = require('node:fs')
const path = require('node:path')

const {
  createArtifact,
  createManifest,
} = require('../scripts/run-data-beta04.js')

const outputDirectory = path.join(__dirname, '..', 'experiments', 'output')

test('Beta 0.4 adds daily segment sensitivity without inventing unavailable channels', () => {
  const first = createArtifact()
  const replay = createArtifact()

  assert.deepEqual(first, replay)
  assert.equal(first.artifactVersion, 'visual-data-beta0.4')
  assert.equal(first.bundle.schemaVersion, 'visual-bundle/1.0')
  assert.equal(first.sensitivity.schemaVersion, 'sensitivity-bundle/1.1')
  assert.equal(first.sensitivity.capabilities.dailySegmentBands, true)
  assert.equal(first.sensitivity.segments.axes.level.timeline.candidate.p50.length, 42 * 5)
  assert.equal(first.sensitivity.capabilities.perAgentBands, false)
  assert.equal(first.sensitivity.capabilities.relationEdges, false)
  assert.equal(first.sensitivity.capabilities.reverseVoice, false)
  assert.equal(first.sensitivity.capabilities.reverseHeat, false)
})

test('checked-in Beta 0.4 artifact matches the current manifest and generated bytes', () => {
  const artifactPath = path.join(outputDirectory, 'visual-data-beta0.4.json')
  const manifestPath = path.join(outputDirectory, 'visual-data-manifest.json')
  const artifactBytes = fs.readFileSync(artifactPath)
  const checkedInArtifact = JSON.parse(artifactBytes.toString('utf8'))
  const checkedInManifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  const generatedArtifact = createArtifact()
  const generatedBytes = Buffer.from(`${JSON.stringify(generatedArtifact)}\n`)

  assert.deepEqual(checkedInArtifact, generatedArtifact)
  assert.deepEqual(checkedInManifest, createManifest(generatedBytes))
  assert.equal(checkedInManifest.manifestVersion, 'visual-data-manifest/1.2')
  assert.equal(checkedInManifest.artifactVersion, 'visual-data-beta0.4')
  assert.equal(checkedInManifest.capabilities.dailySegmentBands, true)
  assert.equal(
    checkedInManifest.sha256,
    crypto.createHash('sha256').update(artifactBytes).digest('hex'),
  )
})
