const test = require('node:test')
const assert = require('node:assert/strict')
const crypto = require('node:crypto')
const fs = require('node:fs')
const path = require('node:path')

const {
  createArtifact,
  createManifest,
} = require('../scripts/run-data-beta03.js')

const outputDirectory = path.join(__dirname, '..', 'experiments', 'output')

test('Beta 0.3 combines deterministic Agent replay with paired sensitivity bands', () => {
  const first = createArtifact()
  const replay = createArtifact()

  assert.deepEqual(first, replay)
  assert.equal(first.artifactVersion, 'visual-data-beta0.3')
  assert.equal(first.bundle.schemaVersion, 'visual-bundle/1.0')
  assert.equal(first.sensitivity.schemaVersion, 'sensitivity-bundle/1.0')
  assert.equal(first.sensitivity.sampleDesign.runs, 100)
  assert.equal(first.sensitivity.timeline.dayCount, 42)
  assert.equal(first.sensitivity.capabilities.perAgentBands, false)
  assert.equal(first.inputs.evidence.caseId, 'C1')
  assert.equal(first.inputs.evidence.grade, 'B')
  assert.equal(first.inputs.evidence.parameterStatus, 'researcher-assumption')
  assert.ok(first.sensitivity.outcomes.delta.finalRisk.p50 < 0)
})

test('checked-in Beta 0.3 artifact matches the current manifest and generated bytes', () => {
  const artifactPath = path.join(outputDirectory, 'visual-data-beta0.3.json')
  const manifestPath = path.join(outputDirectory, 'visual-data-manifest.json')
  const artifactBytes = fs.readFileSync(artifactPath)
  const checkedInArtifact = JSON.parse(artifactBytes.toString('utf8'))
  const checkedInManifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  const generatedArtifact = createArtifact()
  const generatedBytes = Buffer.from(`${JSON.stringify(generatedArtifact)}\n`)

  assert.deepEqual(checkedInArtifact, generatedArtifact)
  assert.deepEqual(checkedInManifest, createManifest(generatedBytes))
  assert.equal(checkedInManifest.artifactVersion, 'visual-data-beta0.3')
  assert.equal(checkedInManifest.capabilities.dailyAggregateBands, true)
  assert.equal(
    checkedInManifest.sha256,
    crypto.createHash('sha256').update(artifactBytes).digest('hex'),
  )
})
